### ISSUE TITLE
Manually Added Plugins not showing up in Agent DVR

### ISSUE THREAD

**Issue by Tornadoalley** [ispysoftware/AgentDVR-Plugins#1]
Likely my user error but when I created a folder via the Agent directory within program files, I named it "Plugins" as the instructions specified. However, upon restarting agent, the plugins still do not appear.
![image](https://user-images.githubusercontent.com/73433060/183938534-85644685-d251-45b7-b4b7-53f1f82b18f9.png)
![image](https://user-images.githubusercontent.com/73433060/183938647-3d5c3c44-f61d-448c-ba31-742d1da0f406.png)
![image](https://user-images.githubusercontent.com/73433060/183939000-93991952-fc5b-477b-b0ba-763d71c4d1ba.png)

**Comment by ispysoftware** [comment]
you'll need to restart it and failing that check the logs at /logs.html
